### ISSUE TITLE
Error on flamecord start 

### ISSUE THREAD

**Issue by RickyLaChow** [LoneDev6/BungeePackFix#35]
I'm using Flamecord v1.5.5, i got this error with latest version 1.1.2

[11:38:35] [main/ERROR]: java.lang.ClassCastException: class java.util.LinkedHashMap$Entry cannot be cast to class java.lang.Integer (java.util.LinkedHashMap$Entry and java.lang.Integer are in module java.base of loader 'bootstrap')
[11:38:35] [main/ERROR]: 	at dev.lone.bungeepackfix.bungee.packets.impl.ClientboundResourcePackPacket.tryInitializingNextReleases(ClientboundResourcePackPacket.java:71)
[11:38:35] [main/ERROR]: 	at dev.lone.bungeepackfix.bungee.packets.impl.ClientboundResourcePackPacket.<clinit>(ClientboundResourcePackPacket.java:57)
[11:38:35] [main/ERROR]: 	at dev.lone.bungeepackfix.bungee.Main.registerPackets(Main.java:83)
[11:38:35] [main/ERROR]: 	at dev.lone.bungeepackfix.bungee.Main.onEnable(Main.java:45)
[11:38:35] [main/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:357)
[11:38:35] [main/ERROR]: 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:311)
[11:38:35] [main/ERROR]: 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52)
[11:38:35] [main/ERROR]: 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[11:38:35] [main/ERROR]: java.lang.reflect.InvocationTargetException
[11:38:35] [main/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:38:35] [main/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[11:38:35] [main/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:38:35] [main/ERROR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[11:38:35] [main/ERROR]: 	at dev.lone.bungeepackfix.bungee.packets.Packets.registerPacket(Packets.java:155)
[11:38:35] [main/ERROR]: 	at dev.lone.bungeepackfix.bungee.packets.impl.ClientboundResourcePackPacket.register(ClientboundResourcePackPacket.java:97)
[11:38:35] [main/ERROR]: 	at dev.lone.bungeepackfix.bungee.Main.registerPackets(Main.java:83)
[11:38:35] [main/ERROR]: 	at dev.lone.bungeepackfix.bungee.Main.onEnable(Main.java:45)
[11:38:35] [main/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:357)
[11:38:35] [main/ERROR]: 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:311)
[11:38:35] [main/ERROR]: 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52)
[11:38:35] [main/ERROR]: 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[11:38:35] [main/ERROR]: Caused by: java.lang.IllegalStateException: Duplicate packet mapping (762, 763)
[11:38:35] [main/ERROR]: 	at com.google.common.base.Preconditions.checkState(Preconditions.java:675)
[11:38:35] [main/ERROR]: 	at net.md_5.bungee.protocol.Protocol$DirectionData.registerPacket(Protocol.java:704)
[11:38:35] [main/ERROR]: 	... 12 more

**Comment by RickyLaChow** [comment]
> Download 1.1.1 and let me know if it works on Minecraft 1.20.1.

Yes working fine with 1.1.1 in 1.20.1

**Comment by LoneDev6** [comment]
So this guy just posted a random issue report without even testing: https://github.com/LoneDev6/BungeePackFix/issues/34
I removed the update from downloads, keep using 1.1.1.
