### ISSUE TITLE
Join Server Problem

### ISSUE THREAD

**Issue by witcharon** [LoneDev6/BungeePackFix#42]
```
[10:38:29 ERROR]: [/46.196.193.189:22021|witcharon] <-> DownstreamBridge <-> [lobby] - encountered exception
java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.PacketWrapper.<init>(net.md_5.bungee.protocol.DefinedPacket, io.netty.buffer.ByteBuf)'
        at dev.lone.bungeepackfix.bungee.packets.impl.ClientboundResourcePackPacket.handle(ClientboundResourcePackPacket.java:82) ~[?:?]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[10:38:29 INFO]: [witcharon] disconnected with: The server you were previously on went down, you have been connected to a fallback server
```

I'm getting this error in the console after logging into the server, and I can't log in.

**Comment by LoneDev6** [comment]
Are you using the latest Bungeecord version?

**Comment by witcharon** [comment]
> Are you using the latest Bungeecord/Waterfall version?

Yes i use latest Waterfall version.

**Comment by witcharon** [comment]
```
messages:
  minimessage_support: false
  ignored_pack:
    enabled: true
    message: "&6Skipped resourcepack installation (you already loaded it)."
equal_pack_attributes:
  hash: true
  forced: true
  prompt_message: true
ignore_hash_in_url: true
main_spigot_server_name: lobby
ignored_servers:
  enabled: true
  invert_check: false
  list:
    - skyblock
log:
  ignored_respack: false
  sent_respack: false
  debug: false
```

this is my config

**Comment by Adreez** [comment]
I am experiencing the same issue with latest waterfall version.

**Comment by GabrielMoreiradeSouza** [comment]
Hello, I am also encountering this issue on my server, and I hope there will be a fix as soon as possible.

**Comment by muuuioi** [comment]
Hello, I am also encountering this issue on my server, and I hope there will be a fix as soon as possible.

**Comment by Nimaari** [comment]
Can confirm it is happening for me too.

**Comment by LoneDev6** [comment]
Can't reproduce on latest Bungeecord version
